#!/bin/bash
# dns.sh
if [ $EUID -ne 0 ]
then
	echo "No tens permisos per executar l'script"
	exit 1
fi
clear
REGEX='^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$'
echo -n "Escriu una direcció IP pel DNS: "
read dns1
echo -n "Escriu un altre: "
read dns2

if [[ $dns1 =~ $REGEX ]] && [[ $dns2 =~ $REGEX ]]
then
	echo "# Generated by NetworkManager" > /etc/resolv.conf
	echo "search Home" >> /etc/resolv.conf
	echo "nameserver $dns1" >> /etc/resolv.conf
	echo "nameserver $dns2" >> /etc/resolv.conf
else
	echo "Format de les IP incorrecte, no es guarden els canvis"
	exit 1
fi
exit 0
